POST http://localhost:8080/v1/feeds
Content-TYpe: application/json
Authorization: ApiKey 7cd105a684903819d96cdaf9a68416e9ead0bcad041a858452ef5686c03eabfe

{
  "name": "medium",
  "url": "https://medium.com"
}