POST http://localhost:8080/v1/feeds
Content-TYpe: application/json
Authorization: ApiKey 3d121f67fb7f849cf09d5eb47d6047731c31fd9ffe89e2a82fe5746c9790e33e

{
  "name": "wagslane.dev",
  "url": "https://wagslane.dev/index.xml"
}