POST http://localhost:8080/v1/feeds
Content-TYpe: application/json
Authorization: ApiKey 651f8750193a52fee10beb66f25f999940c461b3ad404ea586e4065b6023d011

{
  "name": "yahoo",
  "url": "https://yahoo.com"
}